### ISSUE TITLE
Handle Oauth that is in new window vs Iframe

### ISSUE THREAD

**Issue by jamesicon** [Finch-API/react-connect#70] opened 2023-11-09 18:17 UTC
We have been using this with no issue when the payroll provider pops up in an iframe. We are having an issue with a Paycor user who when going through finch connnect, it opens up in a new window instead of an iframe, they log in successfully but the window never closes and our application never receives an access token.

Is there anything special we have to do for when it opens up in a new window vs iframe?

**Comment by M-Shehu** [comment] 2023-12-22 20:24
Thanks for logging an issue. This was caused by the way we used to send the code from the OAuth window to the iFramed Connect the SDK opens. We've since upgraded and improved the code transport mechanism and this shouldn't be an issue any longer. 

I'll close this issue but feel free to re-open it if you encounter any other issues relating to this

**Closed by M-Shehu** 2023-12-22 20:24 UTC

**Comment by jamesicon** [comment] 2023-12-26 21:31
@M-Shehu does this require a package update? I noticed the release version didn't change.

**Comment by M-Shehu** [comment] 2023-12-26 21:48
No it doesn't. The change was made in Finch Connect 😄
